/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class mainView extends javax.swing.JFrame {

   private CardLayout card= null;
    public mainView() {
        initComponents();
        card = (CardLayout) this.pnlMain.getLayout();
        pnlMain.add(new panel_TrangChu(), "Home");
        card.show(this.pnlMain, "Home");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblLogoCuaHang = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pnlThongTinNV = new javax.swing.JPanel();
        lblAnhNV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblQLSP = new javax.swing.JLabel();
        lblQLBH = new javax.swing.JLabel();
        lblQLKH = new javax.swing.JLabel();
        lblQLTK = new javax.swing.JLabel();
        lblTroGiup = new javax.swing.JLabel();
        lblDoiMatKhau = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ MUA BÁN SÁCH");

        pnlTop.setBackground(new java.awt.Color(51, 51, 255));

        lblLogoCuaHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/H2.png"))); // NOI18N
        lblLogoCuaHang.setPreferredSize(new java.awt.Dimension(100, 50));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("CỬA HÀNG MUA BÁN SÁCH TẠI HIỆU SÁCH TƯ NHÂN");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLogoCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLogoCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlLeft.setBackground(new java.awt.Color(51, 102, 255));
        pnlLeft.setPreferredSize(new java.awt.Dimension(255, 629));

        pnlThongTinNV.setBackground(new java.awt.Color(51, 153, 255));

        lblAnhNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Kiều Anh Hải");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("NV-2301");

        javax.swing.GroupLayout pnlThongTinNVLayout = new javax.swing.GroupLayout(pnlThongTinNV);
        pnlThongTinNV.setLayout(pnlThongTinNVLayout);
        pnlThongTinNVLayout.setHorizontalGroup(
            pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlThongTinNVLayout.setVerticalGroup(
            pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                .addGroup(pnlThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinNVLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homePage.png"))); // NOI18N
        lblTrangChu.setText("Trang Chủ");
        lblTrangChu.setOpaque(true);
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
        });

        lblQLSP.setBackground(new java.awt.Color(255, 255, 255));
        lblQLSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQLSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/products.png"))); // NOI18N
        lblQLSP.setText("Quản Lý Sản Phẩm");
        lblQLSP.setOpaque(true);

        lblQLBH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQLBH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/client.png"))); // NOI18N
        lblQLBH.setText("Quản Lý Bán Hàng");
        lblQLBH.setOpaque(true);
        lblQLBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLBHMouseClicked(evt);
            }
        });

        lblQLKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQLKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/client.png"))); // NOI18N
        lblQLKH.setText("Quản Lý Khách Hàng");
        lblQLKH.setOpaque(true);

        lblQLTK.setBackground(new java.awt.Color(204, 255, 255));
        lblQLTK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQLTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        lblQLTK.setText("Quản Lý Thống Kê");
        lblQLTK.setOpaque(true);

        lblTroGiup.setBackground(new java.awt.Color(204, 255, 255));
        lblTroGiup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trợ giúp.jpg"))); // NOI18N
        lblTroGiup.setText("Trợ Giúp");
        lblTroGiup.setOpaque(true);

        lblDoiMatKhau.setBackground(new java.awt.Color(204, 255, 255));
        lblDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/đổi mật khẩu.png"))); // NOI18N
        lblDoiMatKhau.setText("Đổi Mật Khẩu");
        lblDoiMatKhau.setOpaque(true);

        lblDangXuat.setBackground(new java.awt.Color(204, 255, 255));
        lblDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log-out.png"))); // NOI18N
        lblDangXuat.setText("Đăng Xuất");
        lblDangXuat.setOpaque(true);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongTinNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQLBH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDoiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTroGiup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQLTK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlThongTinNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTrangChu)
                .addGap(12, 12, 12)
                .addComponent(lblQLSP)
                .addGap(12, 12, 12)
                .addComponent(lblQLBH)
                .addGap(12, 12, 12)
                .addComponent(lblQLKH)
                .addGap(12, 12, 12)
                .addComponent(lblQLTK)
                .addGap(12, 12, 12)
                .addComponent(lblTroGiup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(lblDoiMatKhau)
                .addGap(18, 18, 18)
                .addComponent(lblDangXuat)
                .addGap(22, 22, 22))
        );

        getContentPane().add(pnlLeft, java.awt.BorderLayout.WEST);

        pnlMain.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        // TODO add your handling code here:
        pnlMain.add(new panel_TrangChu(), "Home");
        card.show(this.pnlMain, "Home");
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblQLBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLBHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQLBHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnhNV;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblLogoCuaHang;
    private javax.swing.JLabel lblQLBH;
    private javax.swing.JLabel lblQLKH;
    private javax.swing.JLabel lblQLSP;
    private javax.swing.JLabel lblQLTK;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lblTroGiup;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlThongTinNV;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
